#!/bin/bash

# Returns filenames and directories, appending a slash to directory names.
_mycmd_compgen_filenames() {
    local cur="$1"

    # Files, excluding directories:
    grep -v -F -f <(compgen -d -P ^ -S '$' -- "$cur") \
        <(compgen -f -P ^ -S '$' -- "$cur") |
        sed -e 's/^\^//' -e 's/\$$/ /'

    # Directories:
    compgen -d -S / -- "$cur"
}

complete_dir_option() {
    local option_name="$1"

    if [[ "$CURRENT" == "$option_name="* ]]; then
        compopt -o nospace

        local path_prefix="${CURRENT#${option_name}=}"

        COMPREPLY=($( compgen -S / -d -- "$path_prefix" ))
        return 0
    fi
}

complete_file_option() {
    local option_name="$1"

    if [[ "$CURRENT" == "$option_name="* ]]; then
        compopt -o nospace

        local file_prefix="${CURRENT#${option_name}=}"
        COMPREPLY=($( _mycmd_compgen_filenames "$file_prefix" ))
        return 0
    fi
}

_cli() {
    local COMMANDS="check install update generate-diff"
    local VALID_TOOLS="diff3 kdiff3 vimdiff meld"
    declare -A OPTIONS_MAPPING=(
        ["global"]="--src="
        ["generate-diff"]="-i --input= --original="
        ["update"]="--all --input= -i --tool= -t"
    )

    COMPREPLY=()
    local CURRENT PREV WORDS
    _get_comp_words_by_ref -n =: -c CURRENT -p PREV -w WORDS
    local COMMAND="global"
    local SRCDIR="/usr/src/"

    # Detect --src=path path
    for word in "${WORDS[@]}"; do
        [[ "$word" == --src=* ]] && SRCDIR="${word#--src=}"
    done

    # Detect command
    for word in "${WORDS[@]}"; do
        case "$word" in
            check|c)
                COMMAND="check"
                break
                ;;
            update|u)
                COMMAND="update"
                break
                ;;
            generate-diff|gd)
                COMMAND="generate-diff"
                break
                ;;
            install|i)
                COMMAND="install"
                break
                ;;
        esac
    done

    if [[ "$COMMAND" == "global" && "$CURRENT" != -* ]]; then
        COMPREPLY=($( compgen -W "$COMMANDS" -- "$CURRENT" ))
        return 0
    fi

    complete_dir_option --src
    complete_file_option --input
    complete_file_option --original

    if [[ "$CURRENT" == -* && "$CURRENT" != *=* ]]; then
        compopt -o nospace
        COMPREPLY=($( compgen -W "${OPTIONS_MAPPING[$COMMAND]}" -- "$CURRENT" ))
    fi

    if [[ "$CURRENT" == "--tool="* ]]; then
        local option="${CURRENT#--tool=}"
        COMPREPLY=($( compgen -W "$VALID_TOOLS" -- "$option" ))
    fi
}

complete -F _cli ./cli
