diff --git a/sys/Makefile b/sys/Makefile
index f3702606f..77f50fbf5 100644
--- a/sys/Makefile
+++ b/sys/Makefile
@@ -4,7 +4,7 @@ CSCOPEDIRS=	bsm cam cddl compat conf contrib crypto ddb dev fs gdb \
 		geom gnu isa kern libkern modules net net80211 \
 		netgraph netinet netinet6 netipsec netpfil \
 		netsmb nfs nfsclient nfsserver nlm ofed opencrypto \
-		rpc security sys ufs vm xdr xen ${CSCOPE_ARCHDIR}
+		rpc security stats sys ufs vm xdr xen ${CSCOPE_ARCHDIR}
 .if !defined(CSCOPE_ARCHDIR)
 .if defined(ALL_ARCH)
 CSCOPE_ARCHDIR = amd64 arm arm64 i386 powerpc riscv x86
