--- orig/sys/Makefile	2025-05-20 16:39:43.641364244 -0300
+++ /tmp/tmp.nCxUQfADNp	2025-05-20 16:39:43.641364244 -0300
@@ -3,7 +3,7 @@
 		geom gnu isa kern libkern modules net net80211 \
 		netgraph netinet netinet6 netipsec netlink netpfil \
 		netsmb nfs nfsclient nfsserver nlm ofed opencrypto \
-		rpc security sys ufs vm xdr xen ${CSCOPE_ARCHDIR}
+		rpc security stats sys ufs vm xdr xen ${CSCOPE_ARCHDIR}
 .if !defined(CSCOPE_ARCHDIR)
 .if defined(ALL_ARCH)
 CSCOPE_ARCHDIR = amd64 arm arm64 i386 powerpc riscv x86
